export const HOME = {
  UPDATE_POPULAR_EXPEDITIONS: 'home/UPDATE_POPULAR_EXPEDITIONS',
  UPDATE_LATEST_EXPEDITIONS: 'home/UPDATE_LATEST_EXPEDITIONS',
  UPDATE_FEATURED_EXPEDITION: 'home/UPDATE_FEATURED_EXPEDITION',
  UPDATE_OBSERVATIONS: 'home/UPDATE_OBSERVATIONS',
  UPDATE_GEOJSON: 'home/UPDATE_GEOJSON',
};
